import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { Disclosure } from "@headlessui/react";
import { MenuIcon, XIcon } from "@heroicons/react/outline";

const items = [
  {
    href: "/",
    title: "Fund DAO",
  },
  {
    href: "/",
    title: "Our Strengths",
  },
  {
    href: "/",
    title: "How it Works",
  },
  {
    href: "/",
    title: "Bridge",
  },
  {
    href: "/",
    title: "Messaging",
  },
  {
    href: "/",
    title: "MetaFrog",
  },
];

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="relative">
        <div className="absolute top-0 w-full">
          <Disclosure as="nav" className="bg-[#061d1e] bg-opacity-60">
            {({ open }) => (
              <>
                <div className="max-w-[1400px] mx-auto px-4 sm:px-6 lg:px-8">
                  <div className="flex items-center justify-between h-16">
                    <div className="flex w-full justify-between items-center">
                      <div className="flex-shrink-0">
                        <img
                          className="block h-8 w-auto"
                          src="./logo.png"
                          alt="Workflow"
                        />
                      </div>
                      <div className="hidden sm:block sm:ml-6">
                        <div className="flex space-x-4">
                          {items.map((item, index) => (
                            <Link key={index} href={item.href}>
                              <a className="px-3 py-2 rounded-md text-[16px] text-[#dce1dd] font-semibold">
                                {item.title}
                              </a>
                            </Link>
                          ))}
                          <div className="px-3 py-2 flex justify-center items-center space-x-3 rounded-md text-[16px] text-[#dce1dd] font-semibold bg-[#041716]">
                            <img
                              className="w-[18px] h-[18px]"
                              src="/avax-logo.png"
                            />
                            <div>Avalanche</div>
                          </div>
                          <div className="flex justify-center items-center">
                            <div className="px-3 py-2 flex justify-center items-center space-x-3 rounded-l-md text-[16px] text-[#dce1dd] bg-[#041716]">
                              <div>25.6 AVAX</div>
                            </div>
                            <div className="px-3 py-2 flex justify-center items-center space-x-3 rounded-md text-[16px] text-white bg-gradient-to-r from-[#D48B47] to-[#6340B7]">
                              0x2B30...70B
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div className="-mr-2 flex sm:hidden">
                      {/* Mobile menu button */}
                      <Disclosure.Button className="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-white hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white">
                        <span className="sr-only">Open main menu</span>
                        {open ? (
                          <XIcon className="block h-6 w-6" aria-hidden="true" />
                        ) : (
                          <MenuIcon
                            className="block h-6 w-6"
                            aria-hidden="true"
                          />
                        )}
                      </Disclosure.Button>
                    </div>
                  </div>
                </div>
                <Disclosure.Panel className="sm:hidden">
                  <div className="px-2 pt-2 pb-3 space-y-1">
                    {items.map((item, index) => (
                      <Link key={index} href={item.href}>
                        <a className="block px-3 py-2 rounded-md text-[16px] text-[#dce1dd] font-semibold">
                          {item.title}
                        </a>
                      </Link>
                    ))}
                  </div>
                </Disclosure.Panel>
              </>
            )}
          </Disclosure>
        </div>
        <div className="h-[1014px] w-full bg-hero object-cover bg-center">
          <div className="h-screen flex flex-col justify-center items-center bg-hero-radial-gradient">
            <h1 className="text-[130px] tracking-[-8.67px] gradient-text">
              Anura
            </h1>
            <p className="w-[633px] text-[17px] text-[#F2FDE7] text-center font-medium">
              A governance-first organization bringing stable investment
              opportunities with consistent returns to decentralized finance.
            </p>
            <div className="mt-10 space-x-5">
              <a className="px-12 py-4 text-[#FDF6F6] text-[13px] font-semibold rounded-lg shadow bg-gradient-to-r from-[#D48B47] to-[#402580]">
                Bridge App
              </a>
              <a className="px-12 py-4 text-[#FDF6F6] text-[13px] font-semibold rounded-lg shadow bg-[#071e21] bg-opacity-60">
                Whitepaper
              </a>
            </div>
          </div>
        </div>
        <div className="">iawe</div>
      </main>

      <footer></footer>
    </div>
  );
};

export default Home;
